name: Unity Build

on:
  push:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.path }} / ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: [ "AntsOrSomething" ]
        version: [ "2019.4.19f1" ]
        target: [ "StandaloneWindows64", "StandaloneLinux64", "StandaloneOSX" ]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
          fetch-depth: 0  # game-ci/unity-builder optionally needs the whole history, for auto versioning

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ matrix.path }}/Library
          key: ${{ matrix.path }}-${{ matrix.version }}-${{ matrix.target }}

      - name: Unity Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: ${{ matrix.path }}
          projectPath: ${{ matrix.path }}
          unityVersion: ${{ matrix.version }}
          targetPlatform: ${{ matrix.target }}
          # allowDirtyBuild: true  # fixes CRLF/LF conversion errors, but dirty

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.path }}.${{ matrix.target }}
          path: build/${{ matrix.target }}
          retention-days: 28
          if-no-files-found: error

      - name: Zip for Release
        run: |
          cd build/${{ matrix.target }}
          zip -r "${{ matrix.path }}.${{ matrix.target }}.zip" * .*
        if: github.event_name == 'release' && github.event.action == 'published'

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: ${{ matrix.path }}.${{ matrix.target }}.zip
          asset_path: ${{ matrix.path }}.${{ matrix.target }}.zip
          asset_content_type: application/zip
        if: github.event_name == 'release' && github.event.action == 'published'