name: Unity Build

on:
  push:
  release:
    types: [published]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.path }} / ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ["AntsOrSomething"]
        version: ["2019.4.20f1"]
        target: ["StandaloneWindows64", "StandaloneLinux64", "StandaloneOSX"]
    
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0  # unity-builder needs the whole history
          submodules: true

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ matrix.path }}/Library
          key: ${{ matrix.path }}-${{ matrix.version }}-${{ matrix.target }}

      - name: Unity Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectPath: ${{ matrix.path }}
          unityVersion: ${{ matrix.version }}
          targetPlatform: ${{ matrix.target }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.path }}.${{ matrix.target }}
          path: build/${{ matrix.target }}
          retention-days: 7
          if-no-files-found: error

      # TODO: upload binaries on release